### ISSUE TITLE
[BUG]:It's not possible to unset IO limits with dellemc.powermax.storagegroup for IOPS

### ISSUE THREAD

**Issue by 212850a** [dell/ansible-powermax#75]
We use dellemc.powermax.storagegroup to set IO limits for storage groups.
The following step we use for that:

`
- name: Set IO limits
  dellemc.powermax.storagegroup:
    unispherehost: "{{ unispherehost }}"
    serial_no: "{{ serial_no }}"
    universion: "{{ universion }}"
    verifycert: "{{ verifycert }}"
    user: "{{ user }}"
    password: "{{ password }}"
    sg_name: "{{ sg_name }}"
    host_io_limit:
      dynamic_distribution: Always
      host_io_limit_iops: 0
      host_io_limit_mbps: 0
    state: present
`

It works fine when we're setting iops & mbps IO limits, but if we want to unset limits for both (iops & mbps) it remove host_io_limit_mbps only, host_io_limit_iops are still left for sg.

**Comment by 212850a** [comment]
@anupamaloke does it mean you confirm that there is a bug? When is your next sprint starts and for how long it lasts?

**Comment by 212850a** [comment]
Is it still opened or closed?

**Comment by doriac11** [comment]
Hello @212850a ,

This is still opened.
The fix is merged, and we are planning to do a release by the end of this month. 
Once the release is completed, I will close the issue.

**Comment by 212850a** [comment]
As far as I see you've closed that issue, but problem is still there even with dell.powermax 4.0.0 collection. 
It is still not possible to unset 'Host I/O Limit (IO/Sec)' with host_io_limit_iops: 0.
